### PR TITLE
Doa 23 select all in custom select widgets

### PR DESCRIPTION
**Pull request by captKuk**
With this commit as compared to the current version used on staging:
- The search icon is visible
- The clear icon in the search field is functional
- The clickable area for the collapse symbol is expanded so that there is no area above, below and left of it that would be interpreted as "Select all of this group".
- The cursor over the caret is a regular mouse pointer as opposed to the hand used for selecting the items.

This doesn't solve the issue with the caret being initialised in the wrong state.

### CODE REVIEW

**Comment by ofir-frd** [comment]
Hey @roiweinreb ,

Could you please take a look and see if you can solve the caret initialization issue?

**Comment by captKuk** [comment]
Hey @ofir-frd , hey @roiweinreb 

There is a solution: If I modify the js-library that provides the multiselect widget, I can set the initial state of the caret. That would come at the price that we need to distribute that library ourselves, e.g. by putting it into the static files of the dashboards using it. I'm not really against it, but it is a bit awkward at the moment. Mostly because we then essentially fork off the multiselect code. As this package has only annual updates - and I would doubt it gets updated at all any more - this might also be viable.

Also, we have a similar construction of code coexisting between the mz-bokeh-package and the dashboards: the loading spinner. It is partially implemented in the `mz-bokeh-package`, but it needs a corresponding js-code (`observe_loading_spinner`) in the apps using it. 

We could also take this as an opportunity to pull the custom widgets out of the `mz-bokeh-package`. Ori pointed out to me recently that there is some proprietary code in this package. And this package is supposed to be public. (right, @oriyudilevich ?)

To see how it works, look at the branch `play_with_bootstrap_multiselect` on mz-bokeh-package. The last commit adds the local copy of the js library to the demo dashboard. There is also a minimal html example in the directory dashboards with a copy of that js library. You can open the html file directly in a browser. Strangely, the change of the js library now only affects the single select widget in the demo-dashboard (I'm pretty sure I had it working also with the multiselect widgets yesterday...).

**Comment by captKuk** [comment]
I now just fixed the orientation of the open/close indicator. That's the behaviour that it had so far, which is not nice. But so far, also nobody complained about it... This also allows us to stick with the current setup.

**Comment by roiweinreb** [comment]
@captKuk I pushed a fix to the caret. 
As I mentioned on slack, I noticed another issue. Currently, every time you select change the value(s) of the widget (by selecting an option from the dropdown), the widget is re-rendered, hence the groups are collapsed/expanded regardless of their state before the selection.

**Review by ofir-frd — APPROVED** [review]
Looking good! The last issue we had with the caret is now solved.

To proceed with merging this branch, I bumped the version to 0.17.2 (we were already at 0.17.1) and merged the staging branch into this one.

**Pull request merged**
