### PR TITLE
MZC-1611-StopUsingLegacyEndpointForItemsUpload

### PR DESCRIPTION
**Pull request by roiweinreb**
Jira ticket: https://materialszone.atlassian.net/browse/MZC-1611

### CODE REVIEW

**Comment by captKuk** [comment]
To me this looks fine. As far as I know, there are only two analysis apps (Cycling and PLQY) that make use of this function. And they still depend on a  very old version of the mz-bokeh-package. There are a couple of changes in the way that would need to be implemented before we get them to work with this current version of the mz-bokeh-package...

@roiweinreb , how urgent is it to stop using the legacy endpoint?

@ofir-frd , do you know of any other apps using this `MaterialsZoneApi.upload` function or the endpoint in general?

**Comment by ofir-frd** [comment]
@roiweinreb , @captKuk  , The analysis repository is currently updated to `mz-bokeh-package` V_0.16.1_, and it is highly likely that it will be updated in the future.

Since the `cycling` and `plq`y apps uses `MaterialsZoneApi.upload` , this PR must be finished together with [AN-2](https://materialszone.atlassian.net/browse/AN-2)

`AN-2` is on our to-do list, so I can take it as my next task if it's a high priority for the back-end.

**Comment by oriyudilevich** [comment]
@ofir-frd (@captKuk) - there's no need to finish this PR before AN-2, Roi just changed /upload/items to /items, both do the same.

**Comment by ofir-frd** [comment]
Ok, Great.
I quickly glanced at it and was concerned that some of the apps might crash over the weekend.

**Pull request merged**
